import Head from "next/head";
import Navbar from "../../compoment/Navbar";
import Socialbuttom from "../../compoment/Socialbuttom";
import { Devicon } from "../../compoment/Devicon";
import BioText from "../../compoment/BioText";
import AllProjet from "../../compoment/AllProjet";
import Footer from "../../compoment/Footer";
import ButtonResume from "../../compoment/ButtonResume";
import ScrollToTop from "react-scroll-to-top";


export default function Home() {
  return (
    <>
      <Head>
        <title>Achraf Dev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>💻</text></svg>"></link>
      </Head>
      <Navbar />
      <ScrollToTop smooth={true} className="flex justify-center items-center"  width="20" height="20"/>
      <section className="grid grid-cols-1 lg:grid-cols-[2fr_1fr] gap-4 mb-4">
        <div className="h-[30rem] bg-gradient-to-r from-cyan-500 to-gray-300 rounded-3xl p-10 gap-16 flex flex-col " >
          
          <BioText />
          
          <div className="flex  flex-col lg:flex-row items-center gap-2  justify-self-end">
            <ButtonResume />
            <Socialbuttom />
          </div>
        </div>
        <div className="h-[30rem] rounded-3xl bg-[url('/IMG_6147-EDIT.jpg')] bg-cover bg-center ">
        </div>      
      </section>
            <Devicon />
      <section id="Projet">
        <AllProjet />
       </section>
      <section id="Contact">
        <Footer />
      </section>
      
    </>
  );
}
